# Generated by Django 5.1.1 on 2024-09-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('product_category', models.CharField(choices=[('Vegetables', 'VEGETABLES'), ('Pulses', 'PULSES'), ('OilCrops', 'OILCROPS'), ('Cereals', 'CEREALS'), ('Stimulantas', 'STIMULANTAS'), ('Spices', 'SPICES'), ('Fibres', 'FIBRES'), ('Fodder Crops', 'FODDER CROPS'), ('Nuts', 'NUTS'), ('Roots', 'ROOTS'), ('Sugar Crops', 'SUGAR CROPS'), ('Others', 'OTHERS')], max_length=25)),
                ('audio_file', models.FileField(blank=True, upload_to='media/audio/')),
            ],
        ),
    ]
