# Generated by Django 5.1.1 on 2024-09-06 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neervana', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_details',
            name='audio_file',
        ),
    ]
