# Generated by Django 5.1.1 on 2024-09-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neervana', '0002_remove_product_details_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Product_details',
        ),
    ]
