# Generated by Django 5.1.1 on 2024-09-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neervana', '0003_product_delete_product_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgricultureProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
            ],
        ),
    ]
