# Generated by Django 5.1.1 on 2024-09-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neervana', '0004_agricultureproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgricultureProduct',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='District',
            field=models.CharField(default='PATNA', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='avrainfall',
            field=models.IntegerField(default=125),
        ),
        migrations.AddField(
            model_name='product',
            name='crop',
            field=models.CharField(default='Apples', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='crop_yield_t_ha',
            field=models.FloatField(default=4),
        ),
        migrations.AddField(
            model_name='product',
            name='harvarea_ha',
            field=models.FloatField(default=43408780.0),
        ),
        migrations.AddField(
            model_name='product',
            name='irrigated_harvarea_fraction',
            field=models.FloatField(default=0.61),
        ),
        migrations.AddField(
            model_name='product',
            name='production_t',
            field=models.FloatField(default=138267700.0),
        ),
        migrations.AddField(
            model_name='product',
            name='typesofsoil',
            field=models.CharField(default='tal-bhangar', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='wfb_cr_m3_t',
            field=models.FloatField(default=60),
        ),
        migrations.AddField(
            model_name='product',
            name='wfb_i_m3_t',
            field=models.FloatField(default=750),
        ),
        migrations.AddField(
            model_name='product',
            name='wfg_m3_t',
            field=models.FloatField(default=500),
        ),
    ]
