# Generated by Django 5.1.1 on 2024-09-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neervana', '0005_delete_agricultureproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='District',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
