# Generated by Django 5.1.1 on 2024-09-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neervana', '0006_alter_product_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='District',
            field=models.FloatField(default=-1.70846, max_length=100),
        ),
    ]
