# Generated by Django 5.1.1 on 2024-09-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neervana', '0007_alter_product_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='crop',
            field=models.FloatField(default=0.695206, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='typesofsoil',
            field=models.FloatField(default=0.0, max_length=100),
        ),
    ]
