# Generated by Django 5.1.1 on 2024-09-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neervana', '0008_alter_product_crop_alter_product_typesofsoil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='District',
            field=models.CharField(default=-1.70846, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='crop',
            field=models.CharField(default=0.695206, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='typesofsoil',
            field=models.CharField(default=0.0, max_length=100),
        ),
    ]
